# SPDX-License-Identifier: GPL-2.0-or-later

.test:
  only:
    - branches
    - merge_requests
  tags:
    - saas-linux-medium-amd64

rust-stable:
  extends: .test
  image: rust:latest
  before_script:
    - rustup component add clippy rustfmt
  script:
    - ./lint.sh

rust-1.74:
  extends: rust-stable
  image: rust:1.74

minimum-dependency-versions:
  extends: .test
  image: rust:1.74
  before_script:
    - rustup toolchain add nightly
    - cargo +nightly install cargo-hack cargo-minimal-versions --locked
  script:
    - cargo minimal-versions check --workspace
