---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/crun-vm.spec

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      fedora-all-x86_64: {}
      fedora-all-aarch64: {}
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
    additional_repos:
      - "copr://rhcontainerbot/podman-next"
    enable_net: true

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # Unit tests
  - job: tests
    trigger: pull_request
    skip_build: true
    targets:
      - fedora-all-aarch64
      - fedora-all-x86_64
    identifier: unit_test
    tmt_plan: "/plans/unit_test"

  # Validate test
  - job: tests
    trigger: pull_request
    skip_build: true
    targets:
      # Only need to test on one target
      - fedora-latest-stable-x86_64
    identifier: validate_test
    tmt_plan: "/plans/validate_test"
